export const listCompany =[
    {
        id:1,
        urlImage:require('@/assets/FSCasino/footer/evolution.png')
    },
    {
        id:2,
        urlImage:require('@/assets/FSCasino/footer/provision.png')
    },
    {
        id:3,
        urlImage:require('@/assets/FSCasino/footer/microgaming.png')
    },
    {
        id:4,
        urlImage:require('@/assets/FSCasino/footer/quickspin.png')
    },
    {
        id:5,
        urlImage:require('@/assets/FSCasino/footer/wmcasino.png')
    },
    {
        id:6,
        urlImage:require('@/assets/FSCasino/footer/evolution.png')
    },
    {
        id:7,
        urlImage:require('@/assets/FSCasino/footer/microgaming.png')
    },
    {
        id:8,
        urlImage:require('@/assets/FSCasino/footer/provision.png')
    }
]