export const companies = [
    {image: 'aux1.png'},
    {image: 'BluePrint.png'},
    {image: 'Booongo.png'},
    {image: 'Bota.png'},
    {image: 'Bota-1.png'},
    {image: 'Bota-2.png'},
    {image: 'cq9.png'},
    {image: 'Elysium.png'},
    {image: 'Elysium-1.png'},
    {image: 'Elysium-2.png'},
    {image: 'Evolution.png'},
    {image: 'Frame 10973.png'},
    {image: 'Frame 10980.png'},
    {image: 'GMW.png'},
    {image: 'GPI.png'},
    {image: 'Habanero.png'},
    {image: 'hs.png'},
    {image: 'Microgaming.png'},
    {image: 'Netent.png'},
    {image: 'Netent-1.png'},
    {image: 'Netent-2.png'},
    {image: 'Netent-3.png'},
    {image: 'Netent-4.png'},
    {image: 'Netent-5.png'},
    {image: 'NLC.png'},
    {image: 'Play N GO.png'},
    {image: 'Playson.png'},
    {image: 'Playson-1.png'},
    {image: 'Pragmatic.png'},
    {image: 'ps.png'},
    {image: 'ps-1.png'},
    {image: 'ps-2.png'},
    {image: 'ps-3.png'},
    {image: 'ps-4.png'},
    {image: 'Quickspin.png'},
    {image: 'Redrake.png'},
    {image: 'Relax.png'},
    {image: 'Skywind.png'},
    {image: 'Spearhead.png'},
    {image: 'Spearhead-1.png'},
    {image: 'Spearhead-2.png'},
    {image: 'Spearhead-3.png'},
    {image: 'Spin Casino.png'},
    {image: 'upg.png'},
    {image: 'upg-1.png'}
]

export const liveCompanies = [
    {image: 'aux1.png'},
    {image: 'BluePrint.png'},
    {image: 'Booongo.png'},
    {image: 'Bota.png'}
]