export const message = [
    {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },{
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "2023-06-08 11:19:51",
    }
];
