export const Icons = {
  // close: require("@/assets/FSCasino/icons/icon-close.png"),
  // closeWhite: require("@/assets/FSCasino/icons/close-white.png"),
  // iconModal: require("@/assets/FSCasino/icons/icon-modal.png"),
  // iconUser: require("@/assets/FSCasino/icons/icon-user.png"),
  // iconHelpCenter: require("@/assets/FSCasino/icons/icon-helpcenter.png"),
  // iconMessage: require("@/assets/FSCasino/icons/icon-message.png"),
  // iconEvent: require("@/assets/FSCasino/icons/icon-calender.png"),
  // user: require("@/assets/FSCasino/icons/User.png"),
  // key: require("@/assets/FSCasino/icons/Key.png"),
  // date: require("@/assets/FSCasino/icons/CalendarCheck.png"),
  // phone: require("@/assets/FSCasino/icons/DeviceMobile.png"),
  // gender: require("@/assets/FSCasino/icons/GenderIntersex.png"),
  // userCircle: require("@/assets/FSCasino/icons/UserCircle.png"),
  // bank: require("@/assets/FSCasino/icons/Bank.png"),
  // userList: require("@/assets/FSCasino/icons/UserList.png"),
  // qrCode: require("@/assets/FSCasino/icons/QrCode.png"),
  check: require("@/assets/CasinoClub/icon/png/jam_check.png"),
  cross: require("@/assets/CasinoClub/icon/png/maki_cross.png"),
  // back: require("@/assets/FSCasino/icons/back.png"),
  // search: require("@/assets/FSCasino/icons/search-icon.png"),
  // edit: require("@/assets/FSCasino/icons/system-uicons_create.png"),
  // game: require("@/assets/FSCasino/icons/game.png"),
  // grid: require("@/assets/FSCasino/icons/GridFour.png"),
  // gridNine: require("@/assets/FSCasino/icons/GridNine.png"),
  // paperclip: require("@/assets/FSCasino/icons/Paperclip.png"),
  // send: require("@/assets/FSCasino/icons/send.png"),
  // mail: require("@/assets/FSCasino/icons/mail-close.png"),
  // mailOpen: require("@/assets/FSCasino/icons/mail-open.png"),
  // iconGameGuide: require("@/assets/FSCasino/gameRule/game-guide-icon.png"),
  // iconDepositHistory: require("@/assets/FSCasino/icons/icon-deposit-history.png"),
  // iconWithdrawHistory: require("@/assets/FSCasino/icons/icon-withdraw-history.png"),
  // play:require("@/assets/FSCasino/icons/play-icon.png"),
  // iconDeposit: require("@/assets/FSCasino/icons/deposit.png"),
  // iconWithdraw: require("@/assets/FSCasino/icons/withdraw.png"),
};
