export const data = [
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  },
  {
    "cu_idx": 5,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "Alo 123 đại bàng gọi se sẻ",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772798
  },
  {
    "cu_idx": 4,
    "cu_type": "",
    "cu_is_delete": "NORMAL",
    "cu_status": "ACTIVE",
    "cu_member_idx": 6,
    "cu_member_nickname": "miu123",
    "cu_invite_code": "AA",
    "cu_question": "ádsdasdasdasd",
    "cu_partner_account": "testagent",
    "cu_answer": "",
    "cu_completed": 0,
    "cu_created": 1689772754
  }
]
