import {converTime} from "@/utils";

export const columns = [
    {
        field: 'status',
        header: 'status',
        isStatus: true

    },
    {
        field: 'subject',
        header: 'subject',
    },
    {
        field: 'date',
        callback: (date) => {
            return converTime(date)
        },
        header: 'date'
    }
]
export const message = [
    {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "Đoạn trường tân thanh contetn",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }, {
        id: 1,
        status: true,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 2,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: false,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    }
];
