import {Images} from "@/const/Image";

export const data = [{
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
}, {
    "no_idx": 65,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event2",
    "no_content": "<p>evnet2Content</p>",
    "no_content_txt": "evnet2TextContent",
    "no_created": 1687256415,
    "no_update": "2023-07-05 07:17:15",
    "no_img_base64": null
}, {
    "no_idx": 63,
    "no_status": "ACTIVE",
    "no_is_delete": "NORMAL",
    "no_type": "NOTICE_EVENT",
    "no_request_ip": "210.99.223.155",
    "no_read_count": 0,
    "no_invite_code": "ROOT",
    "no_partner_account": "cmsadmin",
    "no_subject": "event1",
    "no_content": "<p>event1 content</p>",
    "no_content_txt": "event1 text content",
    "no_created": 1687158252,
    "no_update": "2023-07-03 10:14:24",
    "no_img_base64": null
},

]
