import {converTime} from "@/utils/PlayG3";

export const columns = [
    {
        field: 'index',
        header: "#",
        isIndex: true,
    },
    {
        field: "mm_read_date",
        header: "checkOrNot",
        isStatus: 1,
    },
    {
        field: "mm_subject",
        header: "title",
        style: "width: 35%"
    },
    {
        field: "mm_created",
        callback: (date) => {
            return converTime(date);
        },
        header: "dateOfRequest",
    },
];
export const infoTable = [
    {
        id: 1,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "Đoạn trường tân thanh contetn",
        date: "20230608",
    },
    {
        id: 2,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 3,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 4,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 5,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 6,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 7,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 8,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 9,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 10,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 11,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 12,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 13,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 14,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 15,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 16,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 17,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 18,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 19,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 20,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 21,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 22,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 23,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 24,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 25,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 26,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 27,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 28,
        status: 1,
        write: "Test1",
        subject: "Đoạn trường tân thanh ",
        content: "",
        date: "20230608",
    },
    {
        id: 29,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
    {
        id: 30,
        status: 0,
        write: "Test1",
        subject: "Waiting for response",
        content: "Waiting for response",
        date: "20230608",
    },
];
