
const state = {
    list: null,
    idxActiveContent: null
}

const getters = {
}

const mutations = {
    handleActiveContent(state, payload) {
        state.idxActiveContent = payload
    },
}

const actions = {
}


export default {
    state,
    getters,
    mutations,
    actions
}

const test =[
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },
    {
        no_content:"<p>notice1 content</p>",
        no_content_txt:"notice1 content text",
        no_created:1681440872,
        no_idx:51,
        no_img_base64:null,
        no_invite_code:"ROOT",
        no_is_delete:"NORMAL",
        no_partner_account:"cmsadmin",
        no_read_count:0,
        no_request_ip:"210.99.223.155",
        no_status:"ACTIVE",
        no_subject:"notice1",
        no_type:"NOTICE_FAQ",
        no_update:"2023-06-27 08:37:16",
    },

]