export const gamesProvider = [
  {
    id: "4",
    company_id: "4",
    vendor_id: "4",
    key: "4",
    name: "Allbet",
    logo: require("@/assets/logo/home2/allbet.png"),
    category: "casino",
  },
  {
    id: "30",
    company_id: "30",
    vendor_id: "30",
    key: "30",
    name: "Asia Gaming",
    logo: require("@/assets/logo/home2/ag_activated.png"),
    category: "casino",
  },
  {
    id: "11",
    company_id: "11",
    vendor_id: "11",
    key: "11",
    name: "BBIN",
    logo: require("@/assets/logo/home2/bbin.png"),
    category: "casino",
  },
  {
    id: "29",
    company_id: "29",
    vendor_id: "29",
    key: "29",
    name: "Betsoft",
    logo: require("@/assets/logo/home2/betsoft_activated.png"),
    category: "casino",
  },
  {
    id: "18",
    company_id: "18",
    vendor_id: "18",
    key: "18",
    name: "BGaming",
    logo: require("@/assets/logo/home2/bgaming.png"),
    category: "casino",
  },
  {
    id: "13",
    company_id: "13",
    vendor_id: "13",
    key: "13",
    name: "Booongo",
    logo: require("@/assets/logo/home2/booongo_activated.png"),
    category: "casino",
  },
  {
    id: "26",
    company_id: "26",
    vendor_id: "26",
    key: "26",
    name: "BOTA",
    logo: require("@/assets/logo/home2/okada.png"),
    category: "casino",
  },
  {
    id: "44",
    company_id: "44",
    vendor_id: "44",
    key: "44",
    name: "BOTA Seamless",
    logo: require("@/assets/logo/home2/okada.png"),
    category: "casino",
  },
  {
    id: "20",
    company_id: "20",
    vendor_id: "20",
    key: "20",
    name: "CQ9",
    logo: require("@/assets/logo/home2/cq9_activated.png"),
    category: "casino",
  },
  {
    id: "28",
    company_id: "28",
    vendor_id: "28",
    key: "28",
    name: "Dream Gaming",
    logo: require("@/assets/logo/home2/dreamActive.png"),
    category: "casino",
  },
  {
    id: 999999,
    company_id: 999999,
    vendor_id: 999999,
    key: 999999,
    name: "에볼루션 카지노",
    category: "casino",
    logo: require("@/assets/logo/home2/evolution_activated.png"),
  },
  {
    id: "25",
    company_id: "25",
    vendor_id: "25",
    key: "25",
    name: "에볼루션 카지노",
    category: "casino",
    logo: require("@/assets/logo/home3/evolution.png"),
  },
  {
    id: "33",
    company_id: "33",
    vendor_id: "33",
    key: "33",
    name: "Evoplay",
    logo: require("@/assets/logo/home2/evoplay_activated.png"),
    category: "casino",
  },
  {
    id: "23",
    company_id: "23",
    vendor_id: "23",
    key: "23",
    name: "GameArt",
    logo: require("@/assets/logo/home2/gameart_activated.png"),
    category: "casino",
  },
  {
    id: "42",
    company_id: "42",
    vendor_id: "42",
    key: "42",
    name: "GamePlay Interactive",
    logo: require("@/assets/logo/home2/gameplay.png"),
    category: "casino",
  },
  {
    id: "21",
    company_id: "21",
    vendor_id: "21",
    key: "21",
    name: "Genesis",
    logo: require("@/assets/logo/home2/genesis.png"),
    category: "casino",
  },
  {
    id: "22",
    company_id: "22",
    vendor_id: "22",
    key: "22",
    name: "Habanero",
    logo: require("@/assets/logo/home2/habanero_activated.png"),
    category: "casino",
  },
  {
    id: "8",
    company_id: "8",
    vendor_id: "8",
    key: "8",
    name: "Kiron",
    logo: require("@/assets/logo/home2/kiron.png"),
    category: "casino",
  },
  {
    id: "49",
    company_id: "49",
    vendor_id: "49",
    key: "49",
    name: "LGD Gaming (Dream Tech)",
    logo: require("@/assets/logo/home2/lgdgaming.png"),
    category: "casino",
  },
  {
    id: "1",
    company_id: "1",
    vendor_id: "1",
    key: "1",
    name: "Microgaming",
    logo: require("@/assets/logo/home2/microgaming_activated.png"),
    category: "casino",
  },
  {
    id: "45",
    company_id: "45",
    vendor_id: "45",
    key: "45",
    name: "Motivation",
    logo: require("@/assets/logo/home2/motivation.png"),
    category: "casino",
  },
  {
    id: "40",
    company_id: "40",
    vendor_id: "40",
    key: "40",
    name: "Nolimit City",
    logo: require("@/assets/logo/home2/nolimitcity.png"),
    category: "casino",
  },
  {
    id: "38",
    company_id: "38",
    vendor_id: "38",
    key: "38",
    name: "Oriental Game",
    logo: require("@/assets/logo/home2/orientalgameActive.png"),
    category: "casino",
  },
  {
    id: "32",
    company_id: "32",
    vendor_id: "32",
    key: "32",
    name: "PG Soft",
    logo: require("@/assets/logo/home2/pgsoft_activated.png"),
    category: "casino",
  },
  {
    id: "17",
    company_id: "17",
    vendor_id: "17",
    key: "17",
    name: "Play N Go",
    logo: require("@/assets/logo/home2/playgoActive.png"),
    category: "casino",
  },
  {
    id: "35",
    company_id: "35",
    vendor_id: "35",
    key: "35",
    name: "Playstar",
    logo: require("@/assets/logo/home2/playstar.png"),
    category: "casino",
  },
  {
    id: "27",
    company_id: "27",
    vendor_id: "27",
    key: "27",
    name: "Playtech",
    logo: require("@/assets/logo/home2/playtech.png"),
    category: "casino",
  },
  {
    id: "9",
    company_id: "9",
    vendor_id: "9",
    key: "9",
    name: "Pragmatic Play",
    logo: require("@/assets/logo/home2/pragmatic_activated.png"),
    category: "casino",
  },
  {
    id: "16",
    company_id: "16",
    vendor_id: "16",
    key: "16",
    name: "QTech",
    logo: require("@/assets/logo/home2/qtech.png"),
    category: "casino",
  },
  {
    id: "14",
    company_id: "14",
    vendor_id: "14",
    key: "14",
    name: "Red Rake",
    logo: require("@/assets/logo/home2/redrake_activated.png"),
    category: "casino",
  },
  {
    id: "39",
    company_id: "39",
    vendor_id: "39",
    key: "39",
    name: "Relax Gaming",
    logo: require("@/assets/logo/home2/relax_activated.png"),
    category: "casino",
  },
  {
    id: "31",
    company_id: "31",
    vendor_id: "31",
    key: "31",
    name: "Sexy",
    logo: require("@/assets/logo/home2/sexy.png"),
    category: "casino",
  },
  {
    id: "34",
    company_id: "34",
    vendor_id: "34",
    key: "34",
    name: "Spribe",
    logo: require("@/assets/logo/home2/spribe.png"),
    category: "casino",
  },
  {
    id: "43",
    company_id: "43",
    vendor_id: "43",
    key: "43",
    name: "Top Trend Gaming",
    logo: require("@/assets/logo/home2/toptrend.png"),
    category: "casino",
  },
  {
    id: "41",
    company_id: "41",
    vendor_id: "41",
    key: "41",
    name: "Triple Profits Games",
    logo: require("@/assets/logo/home2/triplepg_activated.png"),
    category: "casino",
  },
  {
    id: "2",
    company_id: "2",
    vendor_id: "2",
    key: "2",
    name: "VIVO",
    logo: require("@/assets/logo/home2/vivo_activated.png"),
    category: "casino",
  },
  {
    id: "46",
    company_id: "46",
    vendor_id: "46",
    key: "46",
    name: "WM Casino",
    logo: require("@/assets/logo/home2/wm_activated.png"),
    category: "casino",
  },
  {
    id: "52",
    company_id: "52",
    vendor_id: "52",
    key: "52",
    name: "WorldMatch",
    logo: require("@/assets/logo/home2/wmr.png"),
    category: "casino",
  },
  {
    id: "3",
    company_id: "3",
    vendor_id: "3",
    key: "3",
    name: "Xpress Technology",
    logo: require("@/assets/logo/home2/vir2al.png"),
    category: "casino",
  },
  {
    id: "51",
    company_id: "51",
    vendor_id: "51",
    key: "51",
    name: "Yggdrasil (ATA)",
    logo: require("@/assets/logo/home2/yggdrasil.png"),
    category: "casino",
  },
  {
    id: "54",
    company_id: "54",
    vendor_id: "54",
    key: "54",
    name: "Pragmatic Play 2",
    logo: require("@/assets/logo/home2/pragmatic_activated.png"),
    category: "casino",
  },
  {
    id: "53",
    company_id: "53",
    vendor_id: "53",
    key: "53",
    name: "Hacksaw Gaming (ATA)",
    logo: require("@/assets/logo/home2/hacksawgaming_activated.png"),
    category: "casino",
  },
  {
    id: "48",
    company_id: "48",
    vendor_id: "48",
    key: "48",
    name: "Playtech LIVE",
    logo: require("@/assets/logo/home2/playtech.png"),
    category: "casino",
  },
  {
    id: "59",
    company_id: "59",
    vendor_id: "59",
    key: "59",
    name: "JiLi",
    logo: require("@/assets/logo/home3/jili.png"),
    category: "casino",
  },
];

export const gamesProviderV1 = [
  {
    id: "4",
    company_id: "4",
    vendor_id: "4",
    key: "4",
    name: "Allbet",
    logo: require("@/assets/logo/home3/allbet.png"),
    category: "casino",
  },
  {
    id: "30",
    company_id: "30",
    vendor_id: "30",
    key: "30",
    name: "Asia Gaming",
    logo: require("@/assets/logo/home3/asia_gaming_2018.png"),
    category: "casino",
  },
  {
    id: "11",
    company_id: "11",
    vendor_id: "11",
    key: "11",
    name: "BBIN",
    logo: require("@/assets/logo/home3/bbin.png"),
    category: "casino",
  },
  {
    id: "29",
    company_id: "29",
    vendor_id: "29",
    key: "29",
    name: "Betsoft",
    logo: require("@/assets/logo/home3/betsoft-logo.png"),
    category: "casino",
  },
  {
    id: "18",
    company_id: "18",
    vendor_id: "18",
    key: "18",
    name: "BGaming",
    logo: require("@/assets/logo/home3/BGaming-LOGO.png"),
    category: "casino",
  },
  {
    id: "13",
    company_id: "13",
    vendor_id: "13",
    key: "13",
    name: "Booongo",
    logo: require("@/assets/logo/home3/booo.png"),
    category: "casino",
  },
  {
    id: "26",
    company_id: "26",
    vendor_id: "26",
    key: "26",
    name: "BOTA",
    logo: require("@/assets/logo/home3/Okada_Manila.png"),
    category: "casino",
  },
  {
    id: "44",
    company_id: "44",
    vendor_id: "44",
    key: "44",
    name: "BOTA Seamless",
    logo: require("@/assets/logo/home3/Okada_Manila.png"),
    category: "casino",
  },
  {
    id: "20",
    company_id: "20",
    vendor_id: "20",
    key: "20",
    name: "CQ9",
    logo: require("@/assets/logo/home3/cq9.png"),
    category: "casino",
  },
  {
    id: "28",
    company_id: "28",
    vendor_id: "28",
    key: "28",
    name: "Dream Gaming",
    logo: require("@/assets/logo/home3/dreamActive.png"),
    category: "casino",
  },
  {
    id: 999999,
    company_id: 999999,
    vendor_id: 999999,
    key: 999999,
    name: "에볼루션 카지노",
    category: "casino",
    logo: require("@/assets/logo/home3/evolution.png"),
  },
  {
    id: "25",
    company_id: "25",
    vendor_id: "25",
    key: "25",
    name: "에볼루션 카지노",
    category: "casino",
    logo: require("@/assets/logo/home3/evolution.png"),
  },
  {
    id: "33",
    company_id: "33",
    vendor_id: "33",
    key: "33",
    name: "Evoplay",
    logo: require("@/assets/logo/home3/evoplay.png"),
    category: "casino",
  },
  {
    id: "23",
    company_id: "23",
    vendor_id: "23",
    key: "23",
    name: "GameArt",
    logo: require("@/assets/logo/home3/gameart.png"),
    category: "casino",
  },
  {
    id: "42",
    company_id: "42",
    vendor_id: "42",
    key: "42",
    name: "GamePlay Interactive",
    logo: require("@/assets/logo/home3/gameplay.png"),
    category: "casino",
  },
  {
    id: "21",
    company_id: "21",
    vendor_id: "21",
    key: "21",
    name: "Genesis",
    logo: require("@/assets/logo/home3/genesis-casino.png"),
    category: "casino",
  },
  {
    id: "22",
    company_id: "22",
    vendor_id: "22",
    key: "22",
    name: "Habanero",
    logo: require("@/assets/logo/home3/habanero.png"),
    category: "casino",
  },
  {
    id: "8",
    company_id: "8",
    vendor_id: "8",
    key: "8",
    name: "Kiron",
    logo: require("@/assets/logo/home3/kiron.png"),
    category: "casino",
  },
  {
    id: "49",
    company_id: "49",
    vendor_id: "49",
    key: "49",
    name: "LGD Gaming (Dream Tech)",
    logo: require("@/assets/logo/home3/ldggaming.png"),
    category: "casino",
  },
  {
    id: "1",
    company_id: "1",
    vendor_id: "1",
    key: "1",
    name: "Microgaming",
    logo: require("@/assets/logo/home3/microgaming.png"),
    category: "casino",
  },
  {
    id: "45",
    company_id: "45",
    vendor_id: "45",
    key: "45",
    name: "Motivation",
    logo: require("@/assets/logo/home3/motivation.png"),
    category: "casino",
  },
  {
    id: "40",
    company_id: "40",
    vendor_id: "40",
    key: "40",
    name: "Nolimit City",
    logo: require("@/assets/logo/home3/nolimit-city-logo.png"),
    category: "casino",
  },
  {
    id: "38",
    company_id: "38",
    vendor_id: "38",
    key: "38",
    name: "Oriental Game",
    logo: require("@/assets/logo/home3/oriental.webp"),
    category: "casino",
  },
  {
    id: "32",
    company_id: "32",
    vendor_id: "32",
    key: "32",
    name: "PG Soft",
    logo: require("@/assets/logo/home3/pocket-games.png"),
    category: "casino",
  },
  {
    id: "17",
    company_id: "17",
    vendor_id: "17",
    key: "17",
    name: "Play N Go",
    logo: require("@/assets/logo/home3/playn-go.png"),
    category: "casino",
  },
  {
    id: "35",
    company_id: "35",
    vendor_id: "35",
    key: "35",
    name: "Playstar",
    logo: require("@/assets/logo/home3/playstart.png"),
    category: "casino",
  },
  {
    id: "27",
    company_id: "27",
    vendor_id: "27",
    key: "27",
    name: "Playtech",
    logo: require("@/assets/logo/home3/Playtech.png"),
    category: "casino",
  },
  {
    id: "9",
    company_id: "9",
    vendor_id: "9",
    key: "9",
    name: "Pragmatic Play",
    logo: require("@/assets/logo/home3/pragmatic.png"),
    category: "casino",
  },
  {
    id: "16",
    company_id: "16",
    vendor_id: "16",
    key: "16",
    name: "QTech",
    logo: require("@/assets/logo/home3/qtech.png"),
    category: "casino",
  },
  {
    id: "14",
    company_id: "14",
    vendor_id: "14",
    key: "14",
    name: "Red Rake",
    logo: require("@/assets/logo/home3/redrake.png"),
    category: "casino",
  },
  {
    id: "39",
    company_id: "39",
    vendor_id: "39",
    key: "39",
    name: "Relax Gaming",
    logo: require("@/assets/logo/home3/relax-gaming.png"),
    category: "casino",
  },
  {
    id: "31",
    company_id: "31",
    vendor_id: "31",
    key: "31",
    name: "Sexy",
    logo: require("@/assets/logo/home3/ae_sexy-main-logo.png"),
    category: "casino",
  },
  {
    id: "34",
    company_id: "34",
    vendor_id: "34",
    key: "34",
    name: "Spribe",
    logo: require("@/assets/logo/home3/spribe847273925.png"),
    category: "casino",
  },
  {
    id: "43",
    company_id: "43",
    vendor_id: "43",
    key: "43",
    name: "Top Trend Gaming",
    logo: require("@/assets/logo/home3/top-trend-gaming-logo.png"),
    category: "casino",
  },
  {
    id: "41",
    company_id: "41",
    vendor_id: "41",
    key: "41",
    name: "Triple Profits Games",
    logo: require("@/assets/logo/home3/TPG.png"),
    category: "casino",
  },
  {
    id: "2",
    company_id: "2",
    vendor_id: "2",
    key: "2",
    name: "VIVO",
    logo: require("@/assets/logo/home3/vivo.png"),
    category: "casino",
  },
  {
    id: "46",
    company_id: "46",
    vendor_id: "46",
    key: "46",
    name: "WM Casino",
    logo: require("@/assets/logo/home3/wm-casino.webp"),
    category: "casino",
  },
  {
    id: "52",
    company_id: "52",
    vendor_id: "52",
    key: "52",
    name: "WorldMatch",
    logo: require("@/assets/logo/home3/WM.png"),
    category: "casino",
  },
  {
    id: "3",
    company_id: "3",
    vendor_id: "3",
    key: "3",
    name: "Xpress Technology",
    logo: require("@/assets/logo/home3/vir2al.png"),
    category: "casino",
  },
  {
    id: "51",
    company_id: "51",
    vendor_id: "51",
    key: "51",
    name: "Yggdrasil (ATA)",
    logo: require("@/assets/logo/home3/yggdrasil.webp"),
    category: "casino",
  },
  {
    id: "54",
    company_id: "54",
    vendor_id: "54",
    key: "54",
    name: "Pragmatic Play 2",
    logo: require("@/assets/logo/home3/pragmatic.png"),
    category: "casino",
  },
  {
    id: "53",
    company_id: "53",
    vendor_id: "53",
    key: "53",
    name: "Hacksaw Gaming (ATA)",
    logo: require("@/assets/logo/home3/hacksawgaming.png"),
    category: "casino",
  },
  {
    id: "48",
    company_id: "48",
    vendor_id: "48",
    key: "48",
    name: "Playtech LIVE",
    logo: require("@/assets/logo/home3/Playtech.png"),
    category: "casino",
  },
  {
    id: "59",
    company_id: "59",
    vendor_id: "59",
    key: "59",
    name: "JiLi",
    logo: require("@/assets/logo/home3/jili.png"),
    category: "casino",
  },
  {
    id: "57",
    company_id: "57",
    vendor_id: "57",
    key: "57",
    name: "1X2 Gaming",
    logo: require("@/assets/logo/home3/1x2gamingActive.png"),
    category: "casino",
    module: 1,
  },
  {
    id: "58",
    company_id: "58",
    vendor_id: "58",
    key: "58",
    name: "Iron Dog Studio",
    logo: require("@/assets/logo/home3/irondog.png"),
    category: "casino",
    module: 1,
  },
  {
    id: "62",
    company_id: "62",
    vendor_id: "62",
    key: "62",
    name: "Leap Gaming",
    logo: require("@/assets/logo/home3/leep.png"),
    category: "casino",
    module: 1,
  },
  {
    id: "999",
    ref: "25",
    company_id: "999",
    vendor_id: "999",
    key: "999",
    name: "netent",
    logo: require("@/assets/logo/home3/netentActive.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "998",
    ref: "25",
    company_id: "998",
    vendor_id: "998",
    key: "998",
    name: "redtiger",
    logo: require("@/assets/logo/home3/redtigerActive.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "997",
    ref: "2",
    company_id: "997",
    vendor_id: "997",
    key: "997",
    name: "spinomenal",
    logo: require("@/assets/logo/home3/spinomenal.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "996",
    ref: "41",
    company_id: "996",
    vendor_id: "996",
    key: "996",
    name: "wazdan",
    logo: require("@/assets/logo/home3/wazdanActive.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "995",
    ref: "16",
    company_id: "995",
    vendor_id: "995",
    key: "995",
    name: "onetouch",
    logo: require("@/assets/logo/home3/onetouchActive.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "994",
    ref: "13",
    company_id: "994",
    vendor_id: "994",
    key: "994",
    name: "playson",
    logo: require("@/assets/logo/home3/playsonActive.png"),
    category: "slot",
    module: 1,
  },
  {
    id: "993",
    ref: "16",
    company_id: "993",
    vendor_id: "993",
    key: "993",
    name: "ezugi",
    logo: require("@/assets/logo/home3/ezugiActive.png"),
    category: "casino",
    module: 1,
  },
  {
    id: "Wazdan",
    ref: "Wazdan",
    company_id: "Wazdan",
    vendor_id: "Wazdan",
    key: "Wazdan",
    name: "wazdan",
    logo: require("@/assets/logo/home3/wazdanActive.png"),
  },
  {
    id: 999991,
    company_id: 999991,
    vendor_id: 999991,
    key: 999991,
    name: "프라그마틱 슬롯",
    category: "slot",
    module: 7,
    logo: require("@/assets/logo/home3/pragmatic.png"),
  },
];
